default: &default
  adapter: postgresql
  encoding: utf8
  pool: 25
  timeout: 5000

  host: localhost
  port: 5432
  username: postgres
  password: postgres

development:
  <<: *default
  database: tinylink_development

test:
  <<: *default
  database: tinylink_test

production:
  <<: *default
  database: tinylink_production
  username: tinylink
  password: <%= ENV['TINYLINK_DATABASE_PASSWORD'] %>
